name: soldepay
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: ^3.6.0

dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.4
  web: any
  sizer: ^3.0.5
  flutter_riverpod: ^2.6.1
  country_picker: ^2.0.27
  country_state_city_picker: ^1.2.8
  intl_phone_field: ^3.2.0
  flutter_secure_storage: ^9.2.4
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  flutter_stripe: ^11.5.0



  file_picker: ^10.2.0
  
  http: any
  webview_flutter: ^4.13.0

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    - assets/secure_card_cardstyle.html
    - assets/card-bg.png
  fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Manrope
      fonts: 
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
