# Lower metaspace, higher heap for jetifier
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

android.enableJetifier=false


# Disable parallelism to reduce memory usage
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false



# Keep AndroidX enabled
android.useAndroidX=true
android.enableJetifier=true
 




